'use strict';
const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');
const crypto = require('node:crypto');
const restorePart = require('./restore-part.js');
const expected = '7670bdc7a1bf13f269afbc025480031ecfc4dacbb6c762d2634f9382f74b77a0';
const parts = Array.from({length:8}, (_, i) => Buffer.from(restorePart(i + 1, fs.readFileSync(path.join(__dirname, `payload-${String(i + 1).padStart(2, '0')}.bin`)))));
const original = zlib.gunzipSync(Buffer.concat(parts));
if (crypto.createHash('sha256').update(original).digest('hex') !== expected || original.length !== 264212) throw new Error('Original catalogue integrity check failed; publication stopped.');
const output = path.join(__dirname, 'public');
fs.mkdirSync(path.join(output, 'assets'), {recursive:true});
const version='2026.09.09-live.3';
const icon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="120" fill="#183e35"/><g fill="#f3dcc1"><ellipse cx="157" cy="214" rx="36" ry="49" transform="rotate(-25 157 214)"/><ellipse cx="220" cy="161" rx="34" ry="48" transform="rotate(-9 220 161)"/><ellipse cx="292" cy="161" rx="34" ry="48" transform="rotate(9 292 161)"/><ellipse cx="355" cy="214" rx="36" ry="49" transform="rotate(25 355 214)"/><path d="M256 240c-35 0-44 27-67 48-20 18-44 38-31 66 12 26 45 25 67 18 20-6 42-6 62 0 22 7 55 8 67-18 13-28-11-48-31-66-23-21-32-48-67-48Z"/></g><path d="m368 97 7 21 22 7-22 7-7 22-7-22-21-7 21-7Z" fill="#eaae85"/></svg>';
fs.writeFileSync(path.join(output,'assets/icon.svg'),icon);
const manifest={id:'./',name:'Pet Gadget Club',short_name:'Pet Gadgets',lang:'en-GB',start_url:'./index.html?source=app',scope:'./',display:'standalone',background_color:'#f7f5ef',theme_color:'#183e35',description:'58 pet-tech and premium robot listings. Reference prices; purchases at external sellers.',icons:[{src:'assets/icon.svg',sizes:'any',type:'image/svg+xml',purpose:'any'}]};
fs.writeFileSync(path.join(output,'manifest.webmanifest'),JSON.stringify(manifest,null,2));
let html=original.toString('utf8').replaceAll('2026.09.09-robots-photos.2',version);
html=html.replace('</head>','<meta name="pgc-package" content="'+version+'"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="Pet Gadgets"><link rel="manifest" href="./manifest.webmanifest"></head>');
fs.writeFileSync(path.join(output,'index.html'),html);
fs.writeFileSync(path.join(output,'robots.txt'),'User-agent: *\nAllow: /\n');
fs.writeFileSync(path.join(output,'sw.js'),`'use strict';
const CACHE='pgc-live-20260909-3';
const INDEX=new URL('./index.html',self.registration.scope).href;
const SHELL=['index.html','manifest.webmanifest','assets/icon.svg'].map(p=>new URL(p,self.registration.scope).href);
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('pgc-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||!e.request.url.startsWith(self.registration.scope))return;
if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();e.waitUntil(caches.open(CACHE).then(c=>c.put(INDEX,copy)))}return r}).catch(()=>caches.match(INDEX)))}
else if(SHELL.includes(e.request.url)){e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)))}
});\n`);
const hash=crypto.createHash('sha256').update(html).digest('hex');
fs.writeFileSync(path.join(output,'release.json'),JSON.stringify({project:'Pet Gadget Club',version,listings:58,premiumRobots:8,originalSha256:expected,sha256:hash,affiliateTracking:false,prices:'Labelled references, not live prices',photos:'External manufacturer or seller URLs'},null,2));
console.log('Verified original catalogue. Built '+version+': 58 listings, 8 robots, app manifest, existing icon and offline shell.');
