(() => {
  function toastSafe(msg){if(typeof toast==='function')toast(msg);else console.log(msg)}
  const stage=document.querySelector('.atom-stage');
  if(stage&&!stage.dataset.upgraded){stage.dataset.upgraded='1';stage.innerHTML='<div class="bvs-logo-card" aria-label="Animated BVS Protocol atom logo"><div class="atom-core"><div class="core-glow"></div><div class="orbit-line o1"></div><div class="orbit-line o2"></div><div class="orbit-line o3"></div><div class="path-plane p1"><div class="hero-sphere">B</div><div class="satellite"></div></div><div class="path-plane p2"><div class="hero-sphere">V</div><div class="satellite"></div></div><div class="path-plane p3"><div class="hero-sphere">S</div><div class="satellite"></div></div></div></div>'}
  const map={today:'D',calendar:'C',protocol:'B',shop:'S',profile:'P'};document.querySelectorAll('[data-view]').forEach(b=>b.dataset.orb=map[b.dataset.view]||'•');
  let deferred=null;
  const isStandalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  const updateStatus=m=>document.querySelectorAll('[data-install-status]').forEach(e=>e.textContent=m);
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;updateStatus('Ready to install')});
  window.addEventListener('appinstalled',()=>{deferred=null;updateStatus('Installed');toastSafe('BVS Protocol installed')});
  async function install(){if(isStandalone()){toastSafe('BVS Protocol is already installed');return}if(deferred){deferred.prompt();const r=await deferred.userChoice;deferred=null;updateStatus(r.outcome==='accepted'?'Installed':'Install available');return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);alert(ios?'On iPhone/iPad: tap Share, then “Add to Home Screen”, then Add.':'Open your browser menu and choose “Install app” or “Add to Home screen”.')}
  const actions=document.querySelector('.hero-actions');if(actions&&!document.getElementById('installAppHero')){const b=document.createElement('button');b.className='btn blue';b.id='installAppHero';b.textContent='Install BVS App';actions.appendChild(b);b.addEventListener('click',install)}
  const today=document.getElementById('today');if(today&&!document.getElementById('bvsInstallStrip')){const div=document.createElement('div');div.id='bvsInstallStrip';div.className='install-strip';div.innerHTML='<img class="install-logo" src="bvs-app-icon.svg" alt="BVS Protocol blue and silver atom app icon"><div><div class="kicker">BVS on your phone</div><h3>Install the BVS Protocol app</h3><p>Add it to your Home Screen with the new blue-and-silver icon. <span data-install-status>'+(isStandalone()?'Installed':'Install available')+'</span></p></div><div class="install-actions"><button class="btn blue" id="installAppMain">Install BVS App</button><a class="btn" href="bvs-app-icon.svg" download="BVS-Protocol-icon.svg">Download logo</a></div>';today.querySelector('.page-head')?.insertAdjacentElement('afterend',div);div.querySelector('#installAppMain').addEventListener('click',install)}
})();