(() => {
  const KEY='bvs_lang_v1';
  const supported=['en','pt','es','fr','it','de'];
  const labels={en:'English',pt:'Português',es:'Español',fr:'Français',it:'Italiano',de:'Deutsch'};
  const dict={
    pt:{'My Day':'Meu dia','Calendar':'Calendário','Profile':'Perfil','Shop':'Loja','Reset demo':'Reiniciar','Today':'Hoje','My BVS Day':'Meu dia BVS','Bioavailability':'Biodisponibilidade','Vitality':'Vitalidade','Synergy':'Sinergia','Foundation':'Base','Builds on B':'Continua B','Complete routine':'Rotina completa','Stage':'Estágio','Taken today':'Tomados hoje','Water':'Água','Completion':'Conclusão','Hydration':'Hidratação','Daily water target':'Meta diária de água','Monthly adherence':'Adesão mensal','Complete':'Completo','Partial':'Parcial','Missed':'Perdido','Personal settings':'Configurações pessoais','Save profile':'Salvar perfil','Recommended supplements':'Suplementos recomendados','Shop Recommended Supplements':'Comprar suplementos recomendados','BVS Shop':'Loja BVS','All products':'Todos os produtos','Taken':'Tomado','Undo':'Desfazer','No record':'Sem registro','Open My BVS Day':'Abrir meu dia BVS','Explore B / V / S':'Explorar B / V / S','Install BVS App':'Instalar App BVS','Install App':'Instalar App','Enable reminders':'Ativar lembretes','Add alarms to calendar':'Adicionar alarmes ao calendário','Test reminder':'Testar lembrete','Smart reminders':'Lembretes inteligentes','Download logo':'Baixar logo'},
    es:{'My Day':'Mi día','Calendar':'Calendario','Profile':'Perfil','Shop':'Tienda','Reset demo':'Reiniciar','Today':'Hoy','My BVS Day':'Mi día BVS','Bioavailability':'Biodisponibilidad','Vitality':'Vitalidad','Synergy':'Sinergia','Foundation':'Base','Builds on B':'Continúa B','Complete routine':'Rutina completa','Stage':'Etapa','Taken today':'Tomados hoy','Water':'Agua','Completion':'Progreso','Hydration':'Hidratación','Daily water target':'Objetivo diario de agua','Monthly adherence':'Adherencia mensual','Complete':'Completo','Partial':'Parcial','Missed':'Omitido','Personal settings':'Ajustes personales','Save profile':'Guardar perfil','Recommended supplements':'Suplementos recomendados','Shop Recommended Supplements':'Comprar suplementos recomendados','BVS Shop':'Tienda BVS','All products':'Todos los productos','Taken':'Tomado','Undo':'Deshacer','No record':'Sin registro','Open My BVS Day':'Abrir mi día BVS','Explore B / V / S':'Explorar B / V / S','Install BVS App':'Instalar BVS App','Enable reminders':'Activar recordatorios','Add alarms to calendar':'Añadir alarmas al calendario','Test reminder':'Probar recordatorio'},
    fr:{'My Day':'Ma journée','Calendar':'Calendrier','Profile':'Profil','Shop':'Boutique','Today':'Aujourd’hui','My BVS Day':'Ma journée BVS','Bioavailability':'Biodisponibilité','Vitality':'Vitalité','Synergy':'Synergie','Foundation':'Base','Complete routine':'Routine complète','Stage':'Étape','Taken today':'Pris aujourd’hui','Water':'Eau','Completion':'Progression','Hydration':'Hydratation','Daily water target':'Objectif quotidien d’eau','Complete':'Complet','Partial':'Partiel','Missed':'Manqué','Save profile':'Enregistrer le profil','Recommended supplements':'Compléments recommandés','Open My BVS Day':'Ouvrir ma journée BVS','Install BVS App':'Installer BVS App','Enable reminders':'Activer les rappels','Add alarms to calendar':'Ajouter au calendrier','Test reminder':'Tester le rappel'},
    it:{'My Day':'La mia giornata','Calendar':'Calendario','Profile':'Profilo','Shop':'Negozio','Today':'Oggi','My BVS Day':'La mia giornata BVS','Bioavailability':'Biodisponibilità','Vitality':'Vitalità','Synergy':'Sinergia','Foundation':'Base','Complete routine':'Routine completa','Stage':'Fase','Taken today':'Assunti oggi','Water':'Acqua','Completion':'Completamento','Hydration':'Idratazione','Daily water target':'Obiettivo giornaliero di acqua','Complete':'Completo','Partial':'Parziale','Missed':'Saltato','Save profile':'Salva profilo','Recommended supplements':'Integratori consigliati','Open My BVS Day':'Apri la mia giornata BVS','Install BVS App':'Installa BVS App','Enable reminders':'Attiva promemoria','Add alarms to calendar':'Aggiungi al calendario','Test reminder':'Prova promemoria'},
    de:{'My Day':'Mein Tag','Calendar':'Kalender','Profile':'Profil','Shop':'Shop','Today':'Heute','My BVS Day':'Mein BVS-Tag','Bioavailability':'Bioverfügbarkeit','Vitality':'Vitalität','Synergy':'Synergie','Foundation':'Grundlage','Complete routine':'Komplette Routine','Stage':'Stufe','Taken today':'Heute genommen','Water':'Wasser','Completion':'Fortschritt','Hydration':'Hydration','Daily water target':'Tägliches Wasserziel','Complete':'Vollständig','Partial':'Teilweise','Missed':'Verpasst','Save profile':'Profil speichern','Recommended supplements':'Empfohlene Supplements','Open My BVS Day':'Meinen BVS-Tag öffnen','Install BVS App':'BVS App installieren','Enable reminders':'Erinnerungen aktivieren','Add alarms to calendar':'Zum Kalender hinzufügen','Test reminder':'Erinnerung testen'}
  };
  const current=()=>{const s=localStorage.getItem(KEY);if(supported.includes(s))return s;const n=(navigator.language||'en').slice(0,2).toLowerCase();return supported.includes(n)?n:'en'};
  function translate(t,l){if(l==='en'||!dict[l])return t;let o=t;for(const [a,b] of Object.entries(dict[l]))o=o.split(a).join(b);return o}
  function translateLeaf(el,l){if(el.closest('#bvsLanguageBox')||el.children.length)return;const original=el.dataset.bvsOriginal||el.textContent;if(!el.dataset.bvsOriginal)el.dataset.bvsOriginal=original;el.textContent=translate(original,l)}
  function apply(l){localStorage.setItem(KEY,l);document.documentElement.lang=l==='pt'?'pt-BR':l;document.querySelectorAll('button,a,h1,h2,h3,strong,small,.kicker,.eyebrow,label').forEach(e=>translateLeaf(e,l));const s=document.getElementById('bvsLangSelect');if(s)s.value=l;window.dispatchEvent(new CustomEvent('bvs-language-change',{detail:{language:l}}))}

  const box=document.createElement('div');box.id='bvsLanguageBox';Object.assign(box.style,{position:'fixed',right:'12px',top:'12px',zIndex:'200',padding:'7px',border:'1px solid rgba(216,239,248,.25)',borderRadius:'14px',background:'rgba(2,8,14,.90)'});
  const sel=document.createElement('select');sel.id='bvsLangSelect';sel.setAttribute('aria-label','Language');Object.assign(sel.style,{minHeight:'38px',width:'auto',borderRadius:'10px',padding:'6px 10px',background:'#071725',color:'#fff',border:'1px solid rgba(216,239,248,.20)'});supported.forEach(l=>{const o=document.createElement('option');o.value=l;o.textContent=labels[l];sel.appendChild(o)});sel.addEventListener('change',e=>apply(e.target.value));box.appendChild(sel);document.body.appendChild(box);

  function addHeadIcon(rel,href,sizes){let link=document.querySelector(`link[rel="${rel}"]`);if(!link){link=document.createElement('link');link.rel=rel;document.head.appendChild(link)}link.href=href;if(sizes)link.sizes=sizes}
  addHeadIcon('icon','bvs-app-icon-192.png','192x192');
  addHeadIcon('apple-touch-icon','bvs-app-icon-192.png','192x192');

  const p=document.createElement('link');p.rel='stylesheet';p.href='bvs-premium.css';document.head.appendChild(p);
  const v=document.createElement('link');v.rel='stylesheet';v.href='bvs-3d-v2.css';document.head.appendChild(v);

  if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}

  function load(src){return new Promise(resolve=>{const s=document.createElement('script');s.src=src;s.async=false;s.onload=resolve;s.onerror=resolve;document.body.appendChild(s)})}
  const lang=current();apply(lang);
  load('bvs-ui-v2.js').then(()=>load('bvs-reminders-v2.js')).then(()=>{apply(current());setTimeout(()=>apply(current()),80)});
})();