(() => {
  const KEY='bvs_lang_v1';
  const supported=['en','pt','es','fr','it','de'];
  const labels={en:'English',pt:'Português',es:'Español',fr:'Français',it:'Italiano',de:'Deutsch'};
  const dict={
    pt:{'My Day':'Meu dia','Calendar':'Calendário','Profile':'Perfil','Shop':'Loja','Reset demo':'Reiniciar','Today':'Hoje','My BVS Day':'Meu dia BVS','Bioavailability':'Biodisponibilidade','Vitality':'Vitalidade','Synergy':'Sinergia','Foundation':'Base','Builds on B':'Continua B','Complete routine':'Rotina completa','Stage':'Estágio','Taken today':'Tomados hoje','Water':'Água','Completion':'Conclusão','Hydration':'Hidratação','Daily water target':'Meta diária de água','Monthly adherence':'Adesão mensal','Complete':'Completo','Partial':'Parcial','Missed':'Perdido','Personal settings':'Configurações pessoais','Save profile':'Salvar perfil','Recommended supplements':'Suplementos recomendados','Shop Recommended Supplements':'Comprar suplementos recomendados','BVS Shop':'Loja BVS','All products':'Todos os produtos','Taken':'Tomado','Undo':'Desfazer','No record':'Sem registro','Open My BVS Day':'Abrir meu dia BVS','Explore B / V / S':'Explorar B / V / S'},
    es:{'My Day':'Mi día','Calendar':'Calendario','Profile':'Perfil','Shop':'Tienda','Reset demo':'Reiniciar','Today':'Hoy','My BVS Day':'Mi día BVS','Bioavailability':'Biodisponibilidad','Vitality':'Vitalidad','Synergy':'Sinergia','Foundation':'Base','Builds on B':'Continúa B','Complete routine':'Rutina completa','Stage':'Etapa','Taken today':'Tomados hoy','Water':'Agua','Completion':'Progreso','Hydration':'Hidratación','Daily water target':'Objetivo diario de agua','Monthly adherence':'Adherencia mensual','Complete':'Completo','Partial':'Parcial','Missed':'Omitido','Personal settings':'Ajustes personales','Save profile':'Guardar perfil','Recommended supplements':'Suplementos recomendados','Shop Recommended Supplements':'Comprar suplementos recomendados','BVS Shop':'Tienda BVS','All products':'Todos los productos','Taken':'Tomado','Undo':'Deshacer','No record':'Sin registro','Open My BVS Day':'Abrir mi día BVS','Explore B / V / S':'Explorar B / V / S'},
    fr:{'My Day':'Ma journée','Calendar':'Calendrier','Profile':'Profil','Shop':'Boutique','Today':'Aujourd’hui','My BVS Day':'Ma journée BVS','Bioavailability':'Biodisponibilité','Vitality':'Vitalité','Synergy':'Synergie','Foundation':'Base','Complete routine':'Routine complète','Stage':'Étape','Taken today':'Pris aujourd’hui','Water':'Eau','Completion':'Progression','Hydration':'Hydratation','Daily water target':'Objectif quotidien d’eau','Complete':'Complet','Partial':'Partiel','Missed':'Manqué','Save profile':'Enregistrer le profil','Recommended supplements':'Compléments recommandés','Open My BVS Day':'Ouvrir ma journée BVS'},
    it:{'My Day':'La mia giornata','Calendar':'Calendario','Profile':'Profilo','Shop':'Negozio','Today':'Oggi','My BVS Day':'La mia giornata BVS','Bioavailability':'Biodisponibilità','Vitality':'Vitalità','Synergy':'Sinergia','Foundation':'Base','Complete routine':'Routine completa','Stage':'Fase','Taken today':'Assunti oggi','Water':'Acqua','Completion':'Completamento','Hydration':'Idratazione','Daily water target':'Obiettivo giornaliero di acqua','Complete':'Completo','Partial':'Parziale','Missed':'Saltato','Save profile':'Salva profilo','Recommended supplements':'Integratori consigliati','Open My BVS Day':'Apri la mia giornata BVS'},
    de:{'My Day':'Mein Tag','Calendar':'Kalender','Profile':'Profil','Shop':'Shop','Today':'Heute','My BVS Day':'Mein BVS-Tag','Bioavailability':'Bioverfügbarkeit','Vitality':'Vitalität','Synergy':'Synergie','Foundation':'Grundlage','Complete routine':'Komplette Routine','Stage':'Stufe','Taken today':'Heute genommen','Water':'Wasser','Completion':'Fortschritt','Hydration':'Hydration','Daily water target':'Tägliches Wasserziel','Complete':'Vollständig','Partial':'Teilweise','Missed':'Verpasst','Save profile':'Profil speichern','Recommended supplements':'Empfohlene Supplements','Open My BVS Day':'Meinen BVS-Tag öffnen'}
  };
  function current(){const s=localStorage.getItem(KEY);if(supported.includes(s))return s;const n=(navigator.language||'en').slice(0,2).toLowerCase();return supported.includes(n)?n:'en'}
  function translateText(text,lang){if(lang==='en'||!dict[lang])return text;let out=text;for(const [a,b] of Object.entries(dict[lang]))out=out.split(a).join(b);return out}
  function apply(lang){localStorage.setItem(KEY,lang);document.documentElement.lang=lang==='pt'?'pt-BR':lang;document.querySelectorAll('[data-bvs-original]').forEach(el=>{el.textContent=translateText(el.dataset.bvsOriginal,lang)});document.querySelectorAll('button,a,h1,h2,h3,strong,small,.kicker,.eyebrow,label').forEach(el=>{if(el.closest('#bvsLanguageBox'))return;if(!el.dataset.bvsOriginal)el.dataset.bvsOriginal=el.textContent;el.textContent=translateText(el.dataset.bvsOriginal,lang)});const s=document.getElementById('bvsLangSelect');if(s)s.value=lang}
  function inject(){if(document.getElementById('bvsLanguageBox'))return;const box=document.createElement('div');box.id='bvsLanguageBox';Object.assign(box.style,{position:'fixed',right:'12px',top:'12px',zIndex:'200',padding:'7px',border:'1px solid rgba(216,239,248,.25)',borderRadius:'14px',background:'rgba(2,8,14,.90)'});const sel=document.createElement('select');sel.id='bvsLangSelect';sel.setAttribute('aria-label','Language');Object.assign(sel.style,{minHeight:'38px',width:'auto',borderRadius:'10px',padding:'6px 10px',background:'#071725',color:'#fff',border:'1px solid rgba(216,239,248,.20)'});for(const l of supported){const o=document.createElement('option');o.value=l;o.textContent=labels[l];sel.appendChild(o)}sel.addEventListener('change',e=>apply(e.target.value));box.appendChild(sel);document.body.appendChild(box)}
  inject();apply(current());
})();