import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {FontLoader} from 'three/addons/loaders/FontLoader.js';
import {TextGeometry} from 'three/addons/geometries/TextGeometry.js';
import {Reflector} from 'three/addons/objects/Reflector.js';
const canvas=document.getElementById('atom'),zone=document.getElementById('atomZone');
let renderer,scene,camera,root,paused=document.body.classList.contains('reduce-motion'),visible=true,t=0,last=performance.now(),drag=false,moved=0,startX=0,startY=0,targetX=.06,targetY=-.14,rotationX=.06,rotationY=-.14,raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),primary=[],rings=[],electrons=[];
const v3=new THREE.Vector3(),q=new THREE.Quaternion();
function material(col,metal=.88,rough=.16){return new THREE.MeshPhysicalMaterial({color:col,metalness:metal,roughness:rough,clearcoat:1,clearcoatRoughness:.06,envMapIntensity:1.6})}
function fallbackLetter(label){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d');ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 320px Georgia';const g=ctx.createLinearGradient(0,100,0,380);g.addColorStop(0,'#ffffff');g.addColorStop(.45,'#deedff');g.addColorStop(.7,'#778b9e');g.addColorStop(1,'#e7f4ff');ctx.fillStyle=g;ctx.shadowColor='#03101f';ctx.shadowBlur=14;ctx.shadowOffsetY=5;ctx.fillText(label,256,278);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1.35,1.35),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false}));mesh.position.z=.827;return mesh}
function makeSphere(stage,phase,col){const group=new THREE.Group();group.userData={stage,phase};const mesh=new THREE.Mesh(new THREE.SphereGeometry(.82,80,64),material(col,.91,.14));mesh.castShadow=mesh.receiveShadow=true;mesh.userData.stage=stage;group.add(mesh);const letter=fallbackLetter(stage);group.add(letter);group.userData.letter=letter;const rim=new THREE.Mesh(new THREE.TorusGeometry(.822,.012,12,96),material(0xa4c2dc,.97,.11));rim.position.z=.02;group.add(rim);primary.push(group);root.add(group)}
function makeRing(z,x,color){const curve=new THREE.EllipseCurve(0,0,3.82,2.33,0,Math.PI*2,false);const path=new THREE.CatmullRomCurve3(curve.getPoints(200).map(p=>new THREE.Vector3(p.x,p.y,0)),true);const ring=new THREE.Mesh(new THREE.TubeGeometry(path,240,.032,10,true),material(color,.96,.16));ring.rotation.set(x,0,z);ring.castShadow=ring.receiveShadow=true;ring.userData={curve,z,x};root.add(ring);rings.push(ring)}
function init(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x050a12,0);scene=new THREE.Scene();scene.fog=new THREE.Fog(0x050a12,19,40);camera=new THREE.PerspectiveCamera(34,1,.1,60);camera.position.set(0,1,13);camera.lookAt(0,.05,0);
const pmrem=new THREE.PMREMGenerator(renderer),env=new RoomEnvironment();scene.environment=pmrem.fromScene(env,.035).texture;env.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight(0xcce7ff,0x0b152c,1.3));const key=new THREE.DirectionalLight(0xe3f0ff,4);key.position.set(-4,7,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.normalBias=.025;key.shadow.bias=-.0002;key.shadow.radius=4;scene.add(key);const fill=new THREE.DirectionalLight(0x71b9ff,2.3);fill.position.set(5,1,3);scene.add(fill);const rimLight=new THREE.DirectionalLight(0x207fea,3);rimLight.position.set(-3,-1,-4);scene.add(rimLight);
const mirror=new Reflector(new THREE.PlaneGeometry(26,24),{textureWidth:640,textureHeight:640,color:0x172234,clipBias:.003});mirror.rotation.x=-Math.PI/2;mirror.position.y=-3.09;scene.add(mirror);const floor=new THREE.Mesh(new THREE.PlaneGeometry(26,24),new THREE.MeshStandardMaterial({color:0x050a12,transparent:true,opacity:.82,roughness:.9,depthWrite:false}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.085;floor.receiveShadow=true;scene.add(floor);
root=new THREE.Group();root.position.y=.15;scene.add(root);makeRing(0,.78,0x85b1da);makeRing(Math.PI/3,-.66,0x1675c5);makeRing(-Math.PI/3,.7,0xb9d1e4);
makeSphere('B',Math.PI*7/6,0x176cb2);makeSphere('V',Math.PI/2,0xa1b7cc);makeSphere('S',Math.PI*11/6,0x246eab);
const core=new THREE.Mesh(new THREE.SphereGeometry(.35,48,40),material(0x225f8c,.96,.1));core.castShadow=true;root.add(core);
for(let i=0;i<9;i++){const electron=new THREE.Mesh(new THREE.SphereGeometry(i%3===0?.16:.1,32,24),material(i%2?0x588fbd:0xc8dced,.97,.12));electron.castShadow=electron.receiveShadow=true;electron.userData={ring:i%3,phase:i*Math.PI*2/3+(i%3)*.8,speed:.2+(i%3)*.035};electrons.push(electron);root.add(electron)}
new FontLoader().load('/vendor/examples/fonts/helvetiker_bold.typeface.json',font=>{primary.forEach(group=>{const geo=new TextGeometry(group.userData.stage,{font,size:.86,depth:.075,curveSegments:8,bevelEnabled:true,bevelThickness:.013,bevelSize:.012,bevelSegments:3});geo.computeBoundingBox();const b=geo.boundingBox;geo.translate(-(b.max.x+b.min.x)/2,-(b.max.y+b.min.y)/2,0);const text=new THREE.Mesh(geo,material(group.userData.stage==='V'?0x143f65:0xe6eff8,.9,.13));text.position.z=.765;text.castShadow=true;text.receiveShadow=true;group.remove(group.userData.letter);group.userData.letter.geometry.dispose();group.userData.letter.material.map.dispose();group.userData.letter.material.dispose();group.add(text)})},undefined,()=>{});
resize();updateObjects();renderer.render(scene,camera);document.getElementById('atomFallback').classList.add('loaded');requestAnimationFrame(frame)}
function resize(){if(!renderer)return;const {width:w,height:h}=zone.getBoundingClientRect();renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.z=Math.max(12.7,4.75/(Math.tan(THREE.MathUtils.degToRad(17))*camera.aspect));camera.position.y=.85;camera.lookAt(0,.05,0);camera.updateProjectionMatrix()}
function updateObjects(){root.rotation.set(rotationX,rotationY,Math.sin(t*.17)*.012);root.updateMatrixWorld(true);root.getWorldQuaternion(q).invert();primary.forEach(group=>{const a=group.userData.phase+t*.085;group.position.set(Math.cos(a)*3.18,Math.sin(a)*1.83,Math.sin(a)*.68+.6);group.quaternion.copy(q).multiply(camera.quaternion)});electrons.forEach(e=>{const ring=rings[e.userData.ring],a=e.userData.phase+t*e.userData.speed;v3.set(Math.cos(a)*3.82,Math.sin(a)*2.33,0).applyEuler(ring.rotation);e.position.copy(v3)});root.updateMatrixWorld(true)}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(!visible||document.hidden)return;if(!paused)t+=dt;rotationX+=(targetX-rotationX)*.065;rotationY+=(targetY-rotationY)*.065;updateObjects();renderer.render(scene,camera)}
canvas.addEventListener('pointerdown',e=>{drag=true;moved=0;startX=e.clientX;startY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-startX,dy=e.clientY-startY;moved+=Math.abs(dx)+Math.abs(dy);targetY=THREE.MathUtils.clamp(targetY+dx*.004,-.65,.65);targetX=THREE.MathUtils.clamp(targetX+dy*.003,-.32,.38);startX=e.clientX;startY=e.clientY});canvas.addEventListener('pointerup',e=>{drag=false;if(moved>8||!camera)return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(primary,true).find(x=>x.object.userData.stage);if(hit)window.dispatchEvent(new CustomEvent('bvs-sphere-select',{detail:{stage:hit.object.userData.stage}}))});canvas.addEventListener('pointercancel',()=>drag=false);
canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')targetY=Math.max(-.65,targetY-.1);else if(e.key==='ArrowRight')targetY=Math.min(.65,targetY+.1);else if(e.key==='ArrowUp')targetX=Math.max(-.32,targetX-.1);else if(e.key==='ArrowDown')targetX=Math.min(.38,targetX+.1);else if(e.code==='Space')document.getElementById('motionButton').click();else return;e.preventDefault()});
document.getElementById('resetAtom').addEventListener('click',()=>{targetX=.06;targetY=-.14;t=0});window.addEventListener('bvs-motion-change',e=>paused=e.detail.paused);new ResizeObserver(resize).observe(zone);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting},{rootMargin:'100px'}).observe(zone);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();document.getElementById('atomFallback').classList.remove('loaded');document.getElementById('atomHint').textContent='3D VIEW PAUSED · RELOAD TO RESTORE'});
try{init()}catch(error){canvas.style.display='none';document.getElementById('atomHint').textContent='BVS · BIOAVAILABILITY, VITALITY, SYNERGY';document.getElementById('motionButton').disabled=true;document.getElementById('resetAtom').disabled=true;console.error('BVS 3D unavailable',error)}
