#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import io
import json
import re
import shutil
import time
import urllib.request
from pathlib import Path

from PIL import Image

PET_LIVE = "https://pettomorrow.com/"
UA = "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/142.0 Mobile Safari/537.36"
PET_RELEASE = "20260916-1"
PET_LOGO_SHA = "7b39d400d307a28ff90cd9a3b6495fc3e4dfe6dcb8497a8db3d243701408c649"
REX_LOGO_SHA = "5c9a2928fabef55fa8eefd2967aebd3499c60a55e66047ff448fe2e7a1462244"

OUT = Path("_site")
REX_SRC = Path("orbit/rex-relax")
REX_OUT = OUT / "rex-relax"
PET_OUT = OUT / "pet-tomorrow"
FREEZE_MANIFEST = Path("/tmp/rex-relax-freeze-hashes.json")

# Exact SHA-256 values from the approved Rex Relax Pages artifact generated by
# successful run 35115380514. A deploy is blocked if any Rex byte changes.
FROZEN_REX_HASHES = {
    "root/index.html": "0bb6345827711320e562303aa4f470b978bde9a06f5e9648b93ee84dea5fb9ab",
    "root/404.html": "0bb6345827711320e562303aa4f470b978bde9a06f5e9648b93ee84dea5fb9ab",
    "index.html": "757f829f48c9d3c12fdf33f8690d1e63db7d8ea08c620127bf54171537ba7c09",
    "manifest.webmanifest": "6b8c8b0c4ecebd67a1c1f245011e57203c7ebe786af04301dbfb1dd8314e299e",
    "sw.js": "eace8419e71a18459118bb8a3047e93a57ae6ae4cc1289bf31985657b6245154",
    "audio-v5-data.js": "9d37e4e021690112e7d5e8a73466d1b2bf354bbb5e4cbe106a1d36b852329cf5",
    "audio-v5.js": "15c4bf9ecf5b2ea0a5ba11db801d60807dff54fcffd9f6ade848d3e7871cc83a",
    "audio-v5-core.js": "934e1654683c2ec528b1416f103410eb8a3bc860d8649c70bbb494069008a142",
    "rex-relax-logo.png": "5c9a2928fabef55fa8eefd2967aebd3499c60a55e66047ff448fe2e7a1462244",
    "icon-192.png": "67297c398372c40ae6a71871a65ad99fd711401554857f178e4a2536ebfc6139",
    "icon-512.png": "555c5930f95c01a19e979aa2830294348ff4b93f09208680ca6702ab397ad94b",
    "icon-512-maskable.png": "deb7f8811066f1536e2a322cc93733b09123aec605a4c49b8b0d7029119619df",
    "apple-touch-icon.png": "580c83f9b17f7a3c7ceb5a0a7037b8583a700c781eb112edd59e097bd1b8a5a9",
}


def fetch(url: str) -> bytes:
    sep = "&" if "?" in url else "?"
    req = urllib.request.Request(
        f"{url}{sep}verify={time.time()}",
        headers={"User-Agent": UA, "Cache-Control": "no-cache"},
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        body = response.read()
        if response.status != 200:
            raise RuntimeError(f"HTTP {response.status}: {url}")
        return body


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def write_exact_rex_manifest_and_worker() -> None:
    manifest = '''{
  "name":"Rex Relax",
  "short_name":"Rex Relax",
  "id":"./",
  "start_url":"./?source=pwa&release=20260916-8",
  "scope":"./",
  "display":"standalone",
  "display_override":["standalone","minimal-ui"],
  "background_color":"#080806",
  "theme_color":"#080806",
  "description":"Rex Relax massage therapy app for sessions, music, client records and consent.",
  "prefer_related_applications":false,
  "icons":[
    {"src":"./icon-192.png?v=20260916-8","sizes":"192x192","type":"image/png","purpose":"any"},
    {"src":"./icon-512.png?v=20260916-8","sizes":"512x512","type":"image/png","purpose":"any"},
    {"src":"./icon-512-maskable.png?v=20260916-8","sizes":"512x512","type":"image/png","purpose":"maskable"}
  ]
}
'''
    worker = '''const CACHE='rex-relax-pages-2026-09-16-8';
const ASSETS=['./','./index.html','./manifest.webmanifest','./rex-relax-logo.png','./icon-192.png','./icon-512.png','./icon-512-maskable.png','./apple-touch-icon.png','./audio-v5-data.js','./audio-v5.js','./audio-v5-core.js'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{await self.clients.claim();for(const k of await caches.keys())if(k.startsWith('rex-relax-pages-')&&k!==CACHE)await caches.delete(k);})()));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==self.location.origin||!u.pathname.includes('/rex-relax/'))return;e.respondWith(fetch(e.request,{cache:'no-cache'}).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone()));return r;}).catch(async()=>await caches.match(e.request)||((e.request.mode==='navigate')?await caches.match('./index.html'):null)||new Response('Unavailable offline',{status:503})));});
'''
    (REX_OUT / "manifest.webmanifest").write_text(manifest, encoding="utf-8")
    (REX_OUT / "sw.js").write_text(worker, encoding="utf-8")


def preserve_rex_exactly() -> None:
    """Rebuild the already-approved Pages package and reject any byte drift."""
    OUT.mkdir(parents=True, exist_ok=True)
    REX_OUT.mkdir(parents=True, exist_ok=True)
    (OUT / ".nojekyll").write_bytes(b"")

    root_html = '<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>Rex Relax fallback host</title></head><body><p><a href="./rex-relax/">Open Rex Relax</a></p></body></html>\n'
    (OUT / "index.html").write_text(root_html, encoding="utf-8")
    (OUT / "404.html").write_text(root_html, encoding="utf-8")

    required = [
        "index.html",
        "audio-v5-data.js",
        "audio-v5.js",
        "audio-v5-core.js",
        "rex-relax-logo.png",
        "icon-192.png",
        "icon-512.png",
        "icon-512-maskable.png",
        "apple-touch-icon.png",
    ]
    for name in required:
        src = REX_SRC / name
        assert src.exists(), f"Rex build output missing: {src}"
        shutil.copyfile(src, REX_OUT / name)

    p = REX_OUT / "index.html"
    text = p.read_text(encoding="utf-8")
    replacements = [
        ("/rex-relax/manifest.webmanifest?v=20260916-8", "./manifest.webmanifest?v=20260916-8"),
        ("/rex-relax/icon-192.png?v=20260916-8", "./icon-192.png?v=20260916-8"),
        ("/rex-relax/icon-512.png?v=20260916-8", "./icon-512.png?v=20260916-8"),
        ("/rex-relax/apple-touch-icon.png?v=20260916-8", "./apple-touch-icon.png?v=20260916-8"),
        ("/rex-relax/audio-v5-data.js?v=20260913-9", "./audio-v5-data.js?v=20260913-9"),
        ("/rex-relax/audio-v5.js?v=20260916-8", "./audio-v5.js?v=20260916-8"),
        ("navigator.serviceWorker.register('/rex-relax/sw.js',{scope:'/rex-relax/'})", "navigator.serviceWorker.register('./sw.js',{scope:'./'})"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    p.write_text(text, encoding="utf-8")

    p = REX_OUT / "audio-v5.js"
    text = p.read_text(encoding="utf-8")
    text = text.replace("'/rex-relax/rex-relax-logo.png?v=20260916-8'", "'./rex-relax-logo.png?v=20260916-8'")
    text = text.replace("'/rex-relax/audio-v5-core.js?v=20260916-2'", "'./audio-v5-core.js?v=20260916-2'")
    p.write_text(text, encoding="utf-8")

    write_exact_rex_manifest_and_worker()

    actual: dict[str, str] = {
        "root/index.html": sha((OUT / "index.html").read_bytes()),
        "root/404.html": sha((OUT / "404.html").read_bytes()),
    }
    for name in FROZEN_REX_HASHES:
        if name.startswith("root/"):
            continue
        actual[name] = sha((REX_OUT / name).read_bytes())
    for name, expected in FROZEN_REX_HASHES.items():
        assert actual[name] == expected, f"REX SEAL VIOLATION {name}: {actual[name]} != {expected}"

    logo = (REX_OUT / "rex-relax-logo.png").read_bytes()
    assert sha(logo) == REX_LOGO_SHA
    data = (REX_OUT / "audio-v5-data.js").read_text(encoding="utf-8")
    assert data.count('"type": "music"') == 20
    assert data.count('"type": "guided"') == 5
    FREEZE_MANIFEST.write_text(json.dumps(FROZEN_REX_HASHES, indent=2, sort_keys=True), encoding="utf-8")
    print("REX_RELAX_SEAL_OK_BYTE_IDENTICAL_TO_APPROVED_ARTIFACT")


def patch_pet_html(html: str) -> str:
    assert "Pet Tomorrow — Clever finds for happier pets" in html
    for text in ("ずっと", "いっしょ", "ペットのもっと明るいあしたへ"):
        assert text in html

    old_icon = re.compile(r'<link href="data:image/svg\+xml,[^"]+" rel="icon"\s*/?>', re.I)
    replacement = "\n".join(
        [
            f'<link rel="manifest" href="./manifest.webmanifest?v={PET_RELEASE}"/>',
            f'<link rel="icon" type="image/png" sizes="192x192" href="./icon-192.png?v={PET_RELEASE}"/>',
            f'<link rel="icon" type="image/png" sizes="512x512" href="./icon-512.png?v={PET_RELEASE}"/>',
            f'<link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png?v={PET_RELEASE}"/>',
            '<meta name="mobile-web-app-capable" content="yes"/>',
            '<meta name="apple-mobile-web-app-capable" content="yes"/>',
            '<meta name="apple-mobile-web-app-title" content="Pet Tomorrow"/>',
            f'<meta name="pgc-package" content="pet-tomorrow-pwa-{PET_RELEASE}"/>',
        ]
    )
    html, count = old_icon.subn(replacement, html, count=1)
    assert count == 1, "Expected exactly one obsolete paw favicon"
    assert "data:image/svg+xml" not in html
    return html


def make_pet_icons(logo_bytes: bytes) -> None:
    image = Image.open(io.BytesIO(logo_bytes)).convert("RGBA")
    assert image.width >= 97 and image.height >= 97
    mascot = image.crop((0, 0, 97, 97))
    resample = Image.Resampling.LANCZOS

    mascot.resize((192, 192), resample).save(PET_OUT / "icon-192.png")
    mascot.resize((512, 512), resample).save(PET_OUT / "icon-512.png")
    mascot.resize((180, 180), resample).save(PET_OUT / "apple-touch-icon.png")
    mascot.resize((1024, 1024), resample).save(PET_OUT / "app-icon-1024.png")

    maskable = Image.new("RGBA", (512, 512), "#183f35")
    safe = mascot.resize((410, 410), resample)
    maskable.alpha_composite(safe, (51, 51))
    maskable.save(PET_OUT / "icon-512-maskable.png")


def build_pet() -> None:
    PET_OUT.mkdir(parents=True, exist_ok=True)
    live_html = fetch(PET_LIVE).decode("utf-8", "replace")
    logo = fetch(PET_LIVE + "pt-logo-strip.png")
    assert logo[:8] == b"\x89PNG\r\n\x1a\n"
    assert sha(logo) == PET_LOGO_SHA, "Pet Tomorrow live logo changed unexpectedly"

    (PET_OUT / "index.html").write_text(patch_pet_html(live_html), encoding="utf-8")
    write(PET_OUT / "pt-logo-strip.png", logo)
    make_pet_icons(logo)

    manifest = {
        "name": "Pet Tomorrow",
        "short_name": "Pet Tomorrow",
        "id": "./",
        "start_url": f"./?source=pwa&release={PET_RELEASE}",
        "scope": "./",
        "display": "standalone",
        "display_override": ["standalone", "minimal-ui"],
        "background_color": "#f7f7f1",
        "theme_color": "#183f35",
        "description": "Pet Tomorrow — clever finds for happier pets.",
        "prefer_related_applications": False,
        "icons": [
            {"src": f"./icon-192.png?v={PET_RELEASE}", "sizes": "192x192", "type": "image/png", "purpose": "any"},
            {"src": f"./icon-512.png?v={PET_RELEASE}", "sizes": "512x512", "type": "image/png", "purpose": "any"},
            {"src": f"./icon-512-maskable.png?v={PET_RELEASE}", "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
        ],
    }
    (PET_OUT / "manifest.webmanifest").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    sw = f"""const CACHE='pet-tomorrow-pwa-{PET_RELEASE}';
const ASSETS=['./','./index.html','./manifest.webmanifest','./pt-logo-strip.png','./icon-192.png','./icon-512.png','./icon-512-maskable.png','./apple-touch-icon.png'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{{await self.clients.claim();for(const k of await caches.keys())if(k.startsWith('pet-tomorrow-pwa-')&&k!==CACHE)await caches.delete(k);}})()));
self.addEventListener('fetch',e=>{{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==self.location.origin||!u.pathname.includes('/pet-tomorrow/'))return;e.respondWith(fetch(e.request,{{cache:'no-cache'}}).then(r=>{{if(r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone()));return r;}}).catch(async()=>await caches.match(e.request)||((e.request.mode==='navigate')?await caches.match('./index.html'):null)||new Response('Unavailable offline',{{status:503}})));}});
"""
    (PET_OUT / "sw.js").write_text(sw, encoding="utf-8")


def verify_local_pet() -> None:
    for pass_no in (1, 2, 3):
        html = (PET_OUT / "index.html").read_text(encoding="utf-8")
        manifest = json.loads((PET_OUT / "manifest.webmanifest").read_text(encoding="utf-8"))
        worker = (PET_OUT / "sw.js").read_text(encoding="utf-8")
        assert sha((PET_OUT / "pt-logo-strip.png").read_bytes()) == PET_LOGO_SHA
        assert "Pet Tomorrow — Clever finds for happier pets" in html
        assert "ずっと" in html and "いっしょ" in html and "ペットのもっと明るいあしたへ" in html
        assert "data:image/svg+xml" not in html
        assert f'pgc-package" content="pet-tomorrow-pwa-{PET_RELEASE}' in html
        assert manifest["name"] == "Pet Tomorrow" and manifest["display"] == "standalone"
        assert manifest["scope"] == "./" and manifest["id"] == "./"
        assert any(icon.get("purpose") == "maskable" for icon in manifest["icons"])
        for name, expected in (
            ("icon-192.png", (192, 192)),
            ("icon-512.png", (512, 512)),
            ("icon-512-maskable.png", (512, 512)),
            ("apple-touch-icon.png", (180, 180)),
            ("app-icon-1024.png", (1024, 1024)),
        ):
            with Image.open(PET_OUT / name) as image:
                assert image.size == expected, (name, image.size)
        assert f"pet-tomorrow-pwa-{PET_RELEASE}" in worker
        print("PET_LOCAL_PASS", pass_no)


def main() -> None:
    preserve_rex_exactly()
    build_pet()
    verify_local_pet()
    print("PAGES_RELEASE_READY_REX_BYTE_FROZEN_PET_TOMORROW_ADDED")


if __name__ == "__main__":
    main()
