/* 20 full-hour extended recordings and five preserved guided sessions. */
globalThis.REX_AUDIO_V5 = {
  "release": "2026.09.13.8",
  "tracks": [
    {
      "name": "Acoustic Revelation",
      "artist": "Indieteur",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/01-acoustic-revelation-60min.mp3",
      "id": "music-acoustic-revelation",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/Revelation_0.mp3",
      "file": "01-acoustic-revelation-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/revelation",
      "license": "CC0-1.0"
    },
    {
      "name": "Lifewave Piano",
      "artist": "The Cynic Project",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/02-lifewave-piano-60min.mp3",
      "id": "music-lifewave-piano",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/006_lifeWave2k_0.mp3",
      "file": "02-lifewave-piano-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/calm-ambient-3-lifewave-2k",
      "license": "CC0-1.0"
    },
    {
      "name": "Peaceful Town",
      "artist": "haruta",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/03-peaceful-town-60min.mp3",
      "id": "music-peaceful-town",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/peaceful_town.mp3",
      "file": "03-peaceful-town-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/peaceful-town-1",
      "license": "CC0-1.0"
    },
    {
      "name": "Plains of Luminescence",
      "artist": "vitalezzz",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/04-plains-of-luminescence-60min.mp3",
      "id": "music-plains-of-luminescence",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/plains_of_luminescence_0.mp3",
      "file": "04-plains-of-luminescence-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/plains-of-luminescence",
      "license": "CC0-1.0"
    },
    {
      "name": "Another August",
      "artist": "The Cynic Project",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/05-another-august-60min.mp3",
      "id": "music-another-august",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/013_Another_August_0.mp3",
      "file": "05-another-august-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/another-august",
      "license": "CC0-1.0"
    },
    {
      "name": "Gentle Piano",
      "artist": "Wolfgang_",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/06-gentle-piano-60min.mp3",
      "id": "music-gentle-piano",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/piano_nostalgia_0.mp3",
      "file": "06-gentle-piano-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/regret-short-emotional-piano",
      "license": "CC0-1.0"
    },
    {
      "name": "Peaceful Ville",
      "artist": "Bobjt",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/07-peaceful-ville-60min.mp3",
      "id": "music-peaceful-ville",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/peaceful_ville_2023_0.mp3",
      "file": "07-peaceful-ville-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/peacefull-ville",
      "license": "CC0-1.0"
    },
    {
      "name": "Pretty Jazz",
      "artist": "Alex McCulloch / Pro Sensory",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/08-pretty-jazz-60min.mp3",
      "id": "music-pretty-jazz",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/pretty_2.mp3",
      "file": "08-pretty-jazz-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/pretty",
      "license": "CC0-1.0"
    },
    {
      "name": "Frets & Strings",
      "artist": "Alex McCulloch / Pro Sensory",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/09-frets-and-strings-60min.mp3",
      "id": "music-frets-strings",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/Frets.mp3",
      "file": "09-frets-and-strings-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/frets",
      "license": "CC0-1.0"
    },
    {
      "name": "Classical Pop",
      "artist": "Alex McCulloch / Pro Sensory",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/10-classical-pop-60min.mp3",
      "id": "music-classical-pop",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/ClassicalPop%20%28Instrumental%29_0.mp3",
      "file": "10-classical-pop-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/classical-pop-instrumental",
      "license": "CC0-1.0"
    },
    {
      "name": "Dream Melody",
      "artist": "jkjkke",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/11-dream-melody-60min.mp3",
      "id": "music-dream-melody",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/jkjkke%20-%20dream_0.mp3",
      "file": "11-dream-melody-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/mainmenu-music",
      "license": "CC0-1.0"
    },
    {
      "name": "I Do Know",
      "artist": "Memoraphile",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/12-i-do-know-60min.mp3",
      "id": "music-i-do-know",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/I_Do_Know_by_Memoraphile_CC0_0.mp3",
      "file": "12-i-do-know-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/i-do-know",
      "license": "CC0-1.0"
    },
    {
      "name": "Vaporware Piano",
      "artist": "The Cynic Project",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/13-vaporware-piano-60min.mp3",
      "id": "music-vaporware-piano",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/003_Vaporware_2.mp3",
      "file": "13-vaporware-piano-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/calm-piano-1-vaporware",
      "license": "CC0-1.0"
    },
    {
      "name": "Gone Fishin' Chill",
      "artist": "iamoneabe",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/14-gone-fishin-chill-60min.mp3",
      "id": "music-gone-fishin-chill",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/gonefishin_0.mp3",
      "file": "14-gone-fishin-chill-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/gone-fishin-0",
      "license": "CC0-1.0"
    },
    {
      "name": "November Snow",
      "artist": "The Cynic Project",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/15-november-snow-60min.mp3",
      "id": "music-november-snow",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/155%20November_snow-33_tape_leveled.mp3",
      "file": "15-november-snow-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/november-snow",
      "license": "CC0-1.0"
    },
    {
      "name": "Calm Journey",
      "artist": "The Cynic Project",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/16-calm-journey-60min.mp3",
      "id": "music-calm-journey",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/001_Synthwave_4k_0.mp3",
      "file": "16-calm-journey-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/calm-ambient-1-synthwave-4k",
      "license": "CC0-1.0"
    },
    {
      "name": "Next to You",
      "artist": "Joth",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/17-next-to-you-60min.mp3",
      "id": "music-next-to-you",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/Next%20to%20You.mp3",
      "file": "17-next-to-you-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/next-to-you",
      "license": "CC0-1.0"
    },
    {
      "name": "Near and Far",
      "artist": "Joth",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/18-near-and-far-60min.mp3",
      "id": "music-near-and-far",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/Near%20and%20Far.mp3",
      "file": "18-near-and-far-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/near-and-far",
      "license": "CC0-1.0"
    },
    {
      "name": "Sirens in Darkness",
      "artist": "The Cynic Project",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/19-sirens-in-darkness-60min.mp3",
      "id": "music-sirens-in-darkness",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/012_Sirens_in_Darkness_0.mp3",
      "file": "19-sirens-in-darkness-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/sirens-in-darkness",
      "license": "CC0-1.0"
    },
    {
      "name": "Fantasy Orchestra",
      "artist": "Joth",
      "url": "https://bvs-protocol.vercel.app/rex-relax/music-60/20-fantasy-orchestra-60min.mp3",
      "id": "music-fantasy-orchestra",
      "type": "music",
      "sourceUrl": "https://opengameart.org/sites/default/files/FantasyOrchestralTheme_1.mp3",
      "file": "20-fantasy-orchestra-60min.mp3",
      "duration": 3600,
      "edition": "60-minute continuous extended recording",
      "sourcePage": "https://opengameart.org/content/fantasy-orchestral-theme",
      "license": "CC0-1.0"
    },
    {
      "id": "guided-breath-body",
      "name": "Breath & Body",
      "type": "guided",
      "method": "Mindful breathing",
      "duration": 5400,
      "url": "https://music.wixstatic.com/mp3/bec34c_d8f539d9b12b43dbb3f3d487a9117476.mp3",
      "voice": "bm_george",
      "narrator": "Deep British male",
      "backgroundCredit": "Gentle Piano \u2014 Wolfgang_; Lifewave Piano \u2014 The Cynic Project; November Snow \u2014 The Cynic Project",
      "coverage": {
        "spokenSegments": 79,
        "first": 0,
        "last": 5350,
        "maxGap": 120.0,
        "denseOpeningSeconds": 900,
        "first15Minutes": {
          "spokenSegments": 40,
          "spokenSeconds": 620.952,
          "spokenFraction": 0.6899,
          "longestPauseSeconds": 7.155,
          "longestAcousticSpeechGapSeconds": 7.4
        }
      },
      "sha256": "087cd491cf30d1feeaa46cdfdb0f242e7c401c5cedca9c9bc527f7b3f2c67170"
    },
    {
      "id": "guided-nervous-system",
      "name": "Quiet Mind",
      "type": "guided",
      "method": "Peaceful-place visualisation",
      "duration": 5400,
      "url": "https://music.wixstatic.com/mp3/bec34c_6c2178f9d6e74fd48523f21c7f088b79.mp3",
      "voice": "bm_george",
      "narrator": "Deep British male",
      "backgroundCredit": "Lifewave Piano \u2014 The Cynic Project; Another August \u2014 The Cynic Project; November Snow \u2014 The Cynic Project",
      "coverage": {
        "spokenSegments": 80,
        "first": 0,
        "last": 5350,
        "maxGap": 120.0,
        "denseOpeningSeconds": 900,
        "first15Minutes": {
          "spokenSegments": 41,
          "spokenSeconds": 591.26,
          "spokenFraction": 0.657,
          "longestPauseSeconds": 7.719,
          "longestAcousticSpeechGapSeconds": 7.9
        }
      },
      "sha256": "1e8c09e0960d5a835033626823b014ee34d341c46a9c94eadf7ea28741b0f373"
    },
    {
      "id": "guided-muscle-release",
      "name": "Full Body Release",
      "type": "guided",
      "method": "Passive muscle relaxation",
      "duration": 5400,
      "url": "https://music.wixstatic.com/mp3/bec34c_2db20399082646e38d99e4009a382123.mp3",
      "voice": "bm_george",
      "narrator": "Deep British male",
      "backgroundCredit": "Dream Melody \u2014 jkjkke; Another August \u2014 The Cynic Project; Gentle Piano \u2014 Wolfgang_",
      "coverage": {
        "spokenSegments": 79,
        "first": 0,
        "last": 5350,
        "maxGap": 120.0,
        "denseOpeningSeconds": 900,
        "first15Minutes": {
          "spokenSegments": 40,
          "spokenSeconds": 595.235,
          "spokenFraction": 0.6614,
          "longestPauseSeconds": 7.815,
          "longestAcousticSpeechGapSeconds": 8.1
        }
      },
      "sha256": "e985a446d883782b0ee10a995ee041df080faf8aa2bcc023d25cd1c2e63d675e"
    },
    {
      "id": "guided-mindful-recovery",
      "name": "Mindful Recovery",
      "type": "guided",
      "method": "Body scan and sensory awareness",
      "duration": 5400,
      "url": "https://music.wixstatic.com/mp3/bec34c_d8cdd6f3e6b94295b043b66cb92b1985.mp3",
      "voice": "bm_george",
      "narrator": "Deep British male",
      "backgroundCredit": "November Snow \u2014 The Cynic Project; Lifewave Piano \u2014 The Cynic Project; Another August \u2014 The Cynic Project",
      "coverage": {
        "spokenSegments": 79,
        "first": 0,
        "last": 5350,
        "maxGap": 120.0,
        "denseOpeningSeconds": 900,
        "first15Minutes": {
          "spokenSegments": 40,
          "spokenSeconds": 625.909,
          "spokenFraction": 0.6955,
          "longestPauseSeconds": 7.028,
          "longestAcousticSpeechGapSeconds": 7.3
        }
      },
      "sha256": "da42d1dfcc3a567ac2d9db49c0bcf693822fd465da02d59007bb461491e38b10"
    },
    {
      "id": "guided-deep-rest",
      "name": "Deep Rest",
      "type": "guided",
      "method": "Rest, warmth and support",
      "duration": 5400,
      "url": "https://music.wixstatic.com/mp3/bec34c_725e5057c46e478db6eeb5e1b155d08c.mp3",
      "voice": "bm_george",
      "narrator": "Deep British male",
      "backgroundCredit": "Another August \u2014 The Cynic Project; November Snow \u2014 The Cynic Project; Lifewave Piano \u2014 The Cynic Project",
      "coverage": {
        "spokenSegments": 80,
        "first": 0,
        "last": 5350,
        "maxGap": 120.0,
        "denseOpeningSeconds": 900,
        "first15Minutes": {
          "spokenSegments": 41,
          "spokenSeconds": 632.638,
          "spokenFraction": 0.7029,
          "longestPauseSeconds": 6.684,
          "longestAcousticSpeechGapSeconds": 7.0
        }
      },
      "sha256": "46478e55c812063e93245a4dfa5c74f24aa368b9ccc6ec696909ecac25fbce0c"
    }
  ]
};
